### ISSUE TITLE
Upload .APK file to Appcenter using Fastlane

### ISSUE THREAD

**Issue by meetsagarlandge25** [microsoft/appcenter-sampleapp-android#46]
am trying to upload a android build (.apk) file to appcenter using fastlane .

this is the fastlane code from Fastfile :
lane :deployAppCenter do
gradle(
task: "clean assembleRelease"`
)

api_token = ENV["APPCENTER_API_TOKEN"]
owner_name = ENV["APPCENTER_OWNER_NAME"]
app_name = ENV["APPCENTER_APP_NAME"]

## You can use the following line to provide a default value if the environment variable doesn't exist
# app_name ||= "appcenter-sampleapp-android"

appcenter_upload(
api_token: api_token,
owner_name: owner_name,
owner_type: "organization", # Default is user - set to organization for appcenter organizations
destinations: "*", # Default is 'Collaborators', use '*' for all distribution groups
app_name: app_name,
file: Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
mapping: Actions.lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH],
notify_testers: false # Set to false if you don't want to notify testers of your new release or true if you do (default: `false`)
)
end
end

C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
42: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
41: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
40: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
39: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
38: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
37: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
36: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
35: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
34: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
33: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
32: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/lane.rb:33:in `call'
31: from Fastfile:40:in `block (2 levels) in parsing_binding'
30: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
29: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
28: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:288:in `run'
22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:254:in `get_or_create_app'
21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:424:in `get_app'
20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/request/encode_json.rb:24:in `call'
16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-nter_helper.rb:424:in `get_app'
19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/request/encode_json.rb:24:in `call'
15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:38:in `call'
11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:85:in `perform_request'
8: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:1228:in `get'
7: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:1470:in `request'
6: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:919:in `start'
5: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
4: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:945:in `connect'
3: from C:/Ruby26-x64/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
2: from C:/Ruby26-x64/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
1: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to api.appcenter.ms:443 (No connection could be made because the target machine actively refused it. - connect(2) for "api.appcenter.ms" port 443) (Errno::ECONNREFUSED)
48: from C:/Ruby26-x64/bin/fastlane:23:in `<main>'
47: from C:/Ruby26-x64/bin/fastlane:23:in `load'
46: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/bin/fastlane:23:in `<top (required)>'
45: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
44: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
43: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
42: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
41: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
40: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
39: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
38: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
37: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
36: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
35: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
34: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
33: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
32: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
31: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/lane.rb:33:in `call'
30: from Fastfile:40:in `block (2 levels) in parsing_binding'
29: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
28: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.139.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:288:in `run'
21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:254:in `get_or_create_app'
20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-plugin-appcenter-1.7.1/lib/fastlane/plugin/appcenter/helper/appcenter_helper.rb:424:in `get_app'
19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:138:in `get'
18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/connection.rb:387:in `run_request'
17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/rack_builder.rb:143:in `build_response'
16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/request/encode_json.rb:24:in `call'
15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:31:in `call'
14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:38:in `call'
11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/faraday-0.17.3/lib/faraday/adapter/net_http.rb:85:in `perform_request'
8: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:1228:in `get'
7: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:1470:in `request'
6: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:919:in `start'
5: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
4: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:945:in `connect'
3: from C:/Ruby26-x64/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
2: from C:/Ruby26-x64/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
1: from C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
C:/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': [!] Failed to open TCP connection to api.appcenter.ms:443 (No connection could be made because the target machine actively refused it. - connect(2) for "api.appcenter.ms" port 443) (Faraday::ConnectionFailed)

**Comment by vyasknellutla** [comment]
Hi @meetsagarlandge25,

I'm sorry to hear about the issue, (and terribly sorry for the delayed response) since this is specific to your application/setup please reach out to us via support (the blue circle button in the bottom right corner of App Center) so we can better investigate the problem.
